hyperparam:
datasettings:


# =============================
# 実験設定ファイル
# =============================

experiment:
  # シナリオ
  scenario:
    pattern_name: "10dim_senario_1"
    model_name: "linear"

  # データセット
  dataset:
    target_number: 210
    source:
      - name: source1
        number: 36
      - name: source2
        number: 24

  # ハイパーパラメータ
  hyperparameters:
    alpha: 1
    split_ratio: 1
    n_trial: 100
    n_split: 5
    n_features: 10
    true_params:
      value: 1
      coffience: [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  
  